# -*- coding: utf-8 -*-
"""python_refresher_june_2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vjepbIE1eLJfrePawB9F2Y0zxPH7v4mn
"""

print('Hello World')

